name: Auto add bump label

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: read
  issues: write

jobs:
  add-bump-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add bump label
        uses: actions-ecosystem/action-add-label@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: bump