name: Auto add bump label

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  add-bump-label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check path files modified
        id: check
        run: |
          git fetch origin ${{ github.event.pull_request.bse.ref }} --depth=1
          CHANGED=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }})
          echo "$CHANGED" | grep -q '^data/schemas/' && echo "match=true" >> $GITHUB_OUTPUT || echo "match=false" >> $GITHUB_OUTPUT
      
      - name: Remove label bumped (se existir)
        if: steps.check.outputs.match == 'true'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: bumped
          number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
      
      - name: Add bump label
        if: steps.check.outputs.match == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: bump-schemas
          number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
